language: python
python: 3.6
branches: master

install:
    - pip install mkdocs 
    - pip install mkdocs-material

# before_script:
#     - mkdir temp
#     - mv * temp
#     - mv .* temp
#     - mv temp/mkdocs.yml .
#     - mv temp/docs .
#     - mv temp/theme .
#     - rm -rf temp

script: 
    - mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: site
  on:
    branch: master