site_name: 'Black MIDI Meta Docs'
site_description: 'Documentation of Black MIDI Meta texts and stuffs.'
site_author: 'Hans5958'
site_url: 'https://hans5958.github.io/Black-MIDI-Meta'
repo_name: 'GitHub'
repo_url: 'https://github.com/Hans5958/Black-MIDI-Meta'

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

nav: 
    - 'Main Page': 'index.md'
    - 'Links': 'links.md'
    # - 'Discord Servers': 'discord.md'
    - 'List of Largest MIDIs':
        - 'Info': 'large-list/index.md'
        - 'Release Notes': 'large-list/release-notes.md'
        - 'Changelog': 'large-list/changelog.md'
        - 'Macros': 'large-list/macros.md'
    - 'Domino Translations': 'domino-translations.md'
    - 'BMC Tags':
        - 'Index': 'tags/index.md'
        - '#': 'tags/%23.md'
        - 'A': 'tags/a.md'
        - 'B': 'tags/b.md'
        - 'C': 'tags/c.md'
        - 'D': 'tags/d.md'
        - 'E': 'tags/e.md'
        - 'F': 'tags/f.md'
        - 'G': 'tags/g.md'
        - 'H': 'tags/h.md'
        - 'I': 'tags/i.md'
        - 'J': 'tags/j.md'
        - 'K': 'tags/k.md'
        - 'L': 'tags/l.md'
        - 'M': 'tags/m.md'
        - 'N': 'tags/n.md'
        - 'O': 'tags/o.md'
        - 'P': 'tags/p.md'
        - 'Q': 'tags/q.md'
        - 'R': 'tags/r.md'
        - 'S': 'tags/s.md'
        - 'T': 'tags/t.md'
        - 'U': 'tags/u.md'
        - 'V': 'tags/v.md'
        - 'W': 'tags/w.md'
        - 'X': 'tags/x.md'
        - 'Y': 'tags/y.md'
        - 'Z': 'tags/z.md'

extra:
  analytics:
    provider: google
    property: G-MFXDVQ0WW7
  consent:
    title: Cookie consent
    description: >- 
      Cookies are used to recognize your repeated visits, as well as to measure the effectiveness of the documentation. With your consent, you're helping to make this documentation better.
    actions:
      - accept
      - reject
      - manage 
